import React from 'react';
import { DocumentCheckIcon } from './Icons';

interface ReportViewProps {
  content: string;
}

export const ReportView: React.FC<ReportViewProps> = ({ content }) => {
  
  // A simple way to highlight the Score if present, without complex parsing
  const scoreMatch = content.match(/🎯.*(评分|Score).*?(\d{1,3})/i);
  const score = scoreMatch ? parseInt(scoreMatch[2]) : null;

  let scoreColor = "text-gray-600";
  let scoreBg = "bg-gray-100";
  if (score !== null) {
      if (score >= 80) { scoreColor = "text-green-600"; scoreBg = "bg-green-100"; }
      else if (score >= 60) { scoreColor = "text-yellow-600"; scoreBg = "bg-yellow-100"; }
      else { scoreColor = "text-red-600"; scoreBg = "bg-red-100"; }
  }

  // Pre-process content to make URLs clickable (basic regex)
  const processText = (text: string) => {
    // Basic Markdown link parser [text](url) replacement could be done here if needed
    // For now, we rely on the CSS markdown styling in index.html and formatting
    return text; 
  };

  return (
    <div className="w-full max-w-4xl mx-auto bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
      {/* Report Header */}
      <div className="bg-slate-50 border-b border-slate-200 p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-100 text-blue-600 rounded-lg">
            <DocumentCheckIcon className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-800">Strategic Analysis Report</h2>
            <p className="text-sm text-slate-500">Generated by Gemini 2.5/3.0 & Google Search</p>
          </div>
        </div>
        
        {score !== null && (
          <div className={`flex flex-col items-center justify-center px-6 py-2 rounded-xl border ${scoreBg} ${scoreColor}`}>
             <span className="text-xs font-semibold uppercase tracking-wider opacity-80">Quality Score</span>
             <span className="text-3xl font-bold">{score}</span>
          </div>
        )}
      </div>

      {/* Markdown Content */}
      <div className="p-6 md:p-10 markdown-body">
          {/* We render preserving whitespace for basic markdown look if libs fail, but CSS handles standard tags */}
          <div dangerouslySetInnerHTML={{ 
              __html: processText(content)
                .replace(/\n/g, '<br />') // Simple line break handling
                // Very basic MD to HTML conversion for headers/bold/tables for visual pop
                // Note: In a real app, use 'react-markdown'
                .replace(/^### (.*$)/gim, '<h3>$1</h3>')
                .replace(/^## (.*$)/gim, '<h2>$1</h2>')
                .replace(/^# (.*$)/gim, '<h1>$1</h1>')
                .replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>')
                .replace(/\|(.+)\|/g, (match) => {
                    // Rudimentary table row wrapper (not perfect but helpful)
                    return match; 
                })
            }} 
          />
          
          {/* Fallback raw display for copy-paste safety */}
          <details className="mt-8 pt-4 border-t border-slate-100">
            <summary className="text-sm text-slate-400 cursor-pointer hover:text-blue-500">View Raw Markdown</summary>
            <pre className="mt-2 p-4 bg-slate-50 rounded-lg text-xs text-slate-600 overflow-x-auto whitespace-pre-wrap">
                {content}
            </pre>
          </details>
      </div>
    </div>
  );
};